### ISSUE TITLE
nsynth generate.py not work

### ISSUE THREAD

**Issue by ruiguo-bio** [tensorflow/magenta-demos#63]
I want to one instrument at a corner, in total 4 instruments, and not a multi-grid. I try two configs, but both  failed. I add some print in generate.py to debug.

I’ve tried that before, and I add some print in the generate.py. Here is the result for the two different configs:

First config:

{
    "instruments": [["single"],
                    ["chorus"],
                    ["bird1"],
                    ["bird5"]],
                    
    "checkpoint_dir":"wavenet-ckpt",
    "pitches":      [36, 40, 44, 48, 52, 56],
    "resolution":              9,
    "final_length":            64000,
    "gpus":                    1,
    "batch_size_embeddings":   32,
    "batch_size_generate":     256,
    "name":         "bird1"
}

Interpolating embeddings between instruments at each pitch...
instrument grid = [['single'], ['chorus'], ['bird1'], ['bird5']]
grid_size = -1e-13
x=[[0.]]
y=[[0.]]
x=[0.]
y=[0.]
xy_grid=<zip object at 0x7f82c8ecaec8>
uv=(0, 0)
Traceback (most recent call last):
  File "generate.py", line 289, in <module>
    interpolate_embeddings()
  File "generate.py", line 131, in interpolate_embeddings
    sub_grid, weights = get_instruments(xy), get_weights(xy)
  File "generate.py", line 114, in get_instruments
    return [instrument_grid[uv[0]][uv[1]],instrument_grid[uv[0]][uv[1]+1],
IndexError: list index out of range

Second config:

{
    "instruments": [["single","chorus","bird1","bird5"]],
    "checkpoint_dir":"wavenet-ckpt",
    "pitches":      [36, 40, 44, 48, 52, 56],
    "resolution":              9,
    "final_length":            64000,
    "gpus":                    1,
    "batch_size_embeddings":   32,
    "batch_size_generate":     256,
    "name":         "bird1"
}

Interpolating embeddings between instruments at each pitch...
instrument grid = [['single', 'chorus', 'bird1', 'bird5']]
grid_size = 2.9999999999999
x=[[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]
 [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
  1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
  3.   ]]
y=[[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.   ]
 [0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125
  0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125
  0.125]
 [0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25
  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25
  0.25 ]
 [0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375
  0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375
  0.375]
 [0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5
  0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5
  0.5  ]
 [0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625
  0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625
  0.625]
 [0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75
  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75
  0.75 ]
 [0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875
  0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875
  0.875]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.
  1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.
  1.   ]
 [1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125
  1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125
  1.125]
 [1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25
  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25
  1.25 ]
 [1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375
  1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375
  1.375]
 [1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5
  1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5
  1.5  ]
 [1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625
  1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625
  1.625]
 [1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75
  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75
  1.75 ]
 [1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875
  1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875
  1.875]
 [2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.
  2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.
  2.   ]
 [2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125
  2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125
  2.125]
 [2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25
  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25
  2.25 ]
 [2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375
  2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375
  2.375]
 [2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5
  2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5
  2.5  ]
 [2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625
  2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625
  2.625]
 [2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75
  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75
  2.75 ]
 [2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875
  2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875
  2.875]
 [3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.
  3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.
  3.   ]]
x=[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25
 1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75
 2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125
 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625
 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.
 1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5
 2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875
 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375
 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75
 0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25
 2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625
 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125
 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5
 0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.
 2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375
 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875
 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25
 0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75
 1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125
 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625
 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.
 0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5
 1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.
 0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25
 1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75
 2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125
 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625
 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.
 1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5
 2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875
 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375
 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625 0.75
 0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125 2.25
 2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5   0.625
 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.    2.125
 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375 0.5
 0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875 2.
 2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25  0.375
 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75  1.875
 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125 0.25
 0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625 1.75
 1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.    0.125
 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5   1.625
 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.    0.
 0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375 1.5
 1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875 3.
 0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.    1.125 1.25  1.375
 1.5   1.625 1.75  1.875 2.    2.125 2.25  2.375 2.5   2.625 2.75  2.875
 3.   ]
y=[0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125
 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125 0.125
 0.125 0.125 0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25
 0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25  0.25
 0.25  0.25  0.25  0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375
 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375 0.375
 0.375 0.375 0.375 0.375 0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5
 0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5   0.5
 0.5   0.5   0.5   0.5   0.5   0.625 0.625 0.625 0.625 0.625 0.625 0.625
 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625 0.625
 0.625 0.625 0.625 0.625 0.625 0.625 0.75  0.75  0.75  0.75  0.75  0.75
 0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.75
 0.75  0.75  0.75  0.75  0.75  0.75  0.75  0.875 0.875 0.875 0.875 0.875
 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875
 0.875 0.875 0.875 0.875 0.875 0.875 0.875 0.875 1.    1.    1.    1.
 1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.    1.
 1.    1.    1.    1.    1.    1.    1.    1.    1.    1.125 1.125 1.125
 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125
 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.125 1.25  1.25
 1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25
 1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.25  1.375
 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375
 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375 1.375
 1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5
 1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5   1.5
 1.5   1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625
 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625 1.625
 1.625 1.625 1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75
 1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75  1.75
 1.75  1.75  1.75  1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875
 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875 1.875
 1.875 1.875 1.875 1.875 2.    2.    2.    2.    2.    2.    2.    2.
 2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.    2.
 2.    2.    2.    2.    2.    2.125 2.125 2.125 2.125 2.125 2.125 2.125
 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125 2.125
 2.125 2.125 2.125 2.125 2.125 2.125 2.25  2.25  2.25  2.25  2.25  2.25
 2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.25
 2.25  2.25  2.25  2.25  2.25  2.25  2.25  2.375 2.375 2.375 2.375 2.375
 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375
 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.375 2.5   2.5   2.5   2.5
 2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5
 2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.5   2.625 2.625 2.625
 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625
 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.625 2.75  2.75
 2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75
 2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.75  2.875
 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875
 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875 2.875
 3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.
 3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.    3.
 3.   ]
xy_grid=<zip object at 0x7f77f1551f48>
uv=(0, 0)
Traceback (most recent call last):
  File "generate.py", line 289, in <module>
    interpolate_embeddings()
  File "generate.py", line 131, in interpolate_embeddings
    sub_grid, weights = get_instruments(xy), get_weights(xy)
  File "generate.py", line 115, in get_instruments
    instrument_grid[uv[0]+1][uv[1]],instrument_grid[uv[0]+1][uv[1]+1]]
IndexError: list index out of range

**Comment by JCBrouwer** [comment]
Hey @ruiguo-bio, I believe this is an issue with the "instruments" setting. The list of lists should be made square.

In your case it should look like this:
`
"instruments": [["single", "chorus"],
                          ["bird1", "bird5"]],
`

**Comment by ruiguo-bio** [comment]
Yes I also tried that settings before. I guess at each corner ableton live 
<img width="611" alt="screen shot 2019-02-18 at 15 39 57" src="https://user-images.githubusercontent.com/20548903/52962014-1f035800-3394-11e9-8805-83a25508f88a.png">
should output only one instrument with no interpolation. But I find it strange that at each corner if I move the interpolation point away and go back to the same corner, the generated sound is different from the last time. At the lower left it's a interpolated sound, and the same happens to lower right. The upper left sometimes no sound and sometimes a few sound, and upper right always no sound. It shows an inconsistent behavior which is quite confusing.

**Comment by JCBrouwer** [comment]
Could you try to running it one more time with the square instruments list after you've removed your working_dir? Could be that some older files leftover from runs with incorrect settings are messing something up.

I'm not quite sure about everything that you've printed out inside the loops but I know that grid_size should come out to 0.9999... if everything is working correctly.

I've just tried to generate a similar single grid and it is generating it correctly for me with the following settings and a clean working_dir:
`
{
    "instruments": [["nhf", "applymoisterizer"],["tinit", "lethmab"]],
    "checkpoint_dir":"~/magenta/magenta/models/nsynth/wavenet-ckpt",
    "pitches":      [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
    "resolution":              9,
    "final_length":            48000,
    "gpus":                    1,
    "batch_size_embeddings":   32,
    "batch_size_generate":     256,
    "name":         "grid_test"
}
`
Note: I've used slightly different pitches and final_length corresponding to my input wav files.
